### ISSUE TITLE
[admission-controller] Does not respect .Values.cert.secret_name

### ISSUE THREAD

**Issue by jstewart612** [lacework/helm-charts#115]
The Secret gets created no matter what.  This value in the values.yaml file is respected in the Deployment object, but a pointless Secret resource is made.  I will be submitting a PR that fixes this oversight.

**Comment by michael-zhou-lw** [comment]
Thanks for raising this issue @jstewart612, this has been added in https://github.com/lacework/helm-charts/pull/148.
