### ISSUE TITLE
clusterAgent is missing resources and using latest tag

### ISSUE THREAD

**Issue by joebowbeer** [lacework/helm-charts#121]
Two items that should be addressed before clusterAgent is released:
* clusterAgent image is configured to use `latest` tag; I assume this should be pinned to a release
* clusterAgent containers do not specify any requests or limits for resources - should it expand resources from values?

**Comment by Israphel** [comment]
bumping this. Release 6.6.0 still points to latest rather than 6.6.0.

CD tools like Argo will not restart the pod because it won't see the change.

**Comment by nschmeller** [comment]
Thanks for the callout -- we've fixed this for upcoming versions (v6.7 and beyond), and I'll modify the current v6.6 charts to include this as well.
