### ISSUE TITLE
lacework-agent chart on k8s 1.23+?

### ISSUE THREAD

**Issue by beyondbill** [lacework/helm-charts#168]
<img width="418" alt="Screen Shot 2023-02-14 at 3 23 46 PM" src="https://user-images.githubusercontent.com/10553863/218854217-10846e35-8427-4bd0-acd2-053109b473ba.png">

The [doc](https://docs.lacework.com/onboarding/deploy-on-kubernetes#supported-versions) says lacework-agent chart is supported on k8s up to 1.22. However this [issue](https://github.com/lacework/helm-charts/issues/47) seems indicate docker should be the only blocker moving on to 1.23. But it has been fixed.

We are considering k8s 1.26 and really wish to use lacework-agent chart there. Could you verify the highest supported k8s version and update the doc accordingly if necessary? Thanks!

**Comment by Israphel** [comment]
I used it in 1.23. They updated the doc but forgot about this issue.

**Comment by nschmeller** [comment]
Hi @Israphel, thanks for the reminder! The docs are updated, so I'll go ahead and close this issue. Please feel free to reopen if anything changes.
