### ISSUE TITLE
v6.6.0 - inconsistant release

### ISSUE THREAD

**Issue by jycamier** [lacework/helm-charts#197]
There's an inconsistance between the release and the image version.
The datacollector image is still in 6.5.2

**Comment by cirego** [comment]
Hi @jycamier, thanks for raising this. I've raised an issue with the team on this

**Comment by catz-lw** [comment]
Thank you @jycamier , the fix is here: https://github.com/lacework/helm-charts/pull/198

We'll put some rails in place to guard against my mistake in the future.

**Comment by catz-lw** [comment]
That fix is at https://github.com/lacework/helm-charts/pull/200

**Comment by catz-lw** [comment]
Please feel free to re-open if #198 didn't resolve the issue.
