### ISSUE TITLE
Duplicated UpdateStrategy Key

### ISSUE THREAD

**Issue by apeschel** [lacework/helm-charts#2]
https://github.com/lacework/helm-charts/blob/main/lacework-agent/templates/daemonset.yaml#L14-L15

https://github.com/lacework/helm-charts/blob/main/lacework-agent/templates/daemonset.yaml#L131-L132

Surprisingly, neither Helm nor Kubernetes seem to care that this key is duplicated. However, flux does refuse to deploy this Helm chart because of this duplication. Also, undefined behavior is never good.

Looks like L14-L15 are a mistaken, and should be removed.

**Comment by apeschel** [comment]
Here's the upstream issue that is involved: https://github.com/kubernetes/kubernetes/issues/14791

**Comment by cirego** [comment]
Hi @apeschel, thanks for reporting. I'll file an internal ticket to track this and fix this shortly.

**Comment by cirego** [comment]
Fixed by #3.
