### ISSUE TITLE
lacework-agent last release - tgz files missing 

### ISSUE THREAD

**Issue by jycamier** [lacework/helm-charts#227]
Hello,

It seams that there's some new release for the `lacework-agent` chart, however the .tgz archive are not release : helm isn't able to download the chart.

**Comment by joebowbeer** [comment]
The latest tgz release in the github registry is 6.9.2 but the [index](https://github.com/lacework/helm-charts/blob/main/index.yaml) shows 6.11.0

The [link](https://support.lacework.com/hc/en-us/articles/360005263034-Deploy-on-Kubernetes#install-using-lacework-charts-repository-recommended) in the [readme](https://github.com/lacework/helm-charts?tab=readme-ov-file#lacework-agent) also points to a missing page.

**Comment by abapat** [comment]
Hi @jycamier, can you provide more information on what is failing/why helm is not able to download the chart? I see the latest [tgz release on github](https://github.com/lacework/helm-charts/blob/main/lacework-agent-6.11.0.tgz) and was able to install properly:
```
$ helm upgrade lacework-agent helm-charts/lacework-agent --install --namespace lacework --create-namespace --set laceworkConfig.accessToken=${token}
Release "lacework-agent" has been upgraded. Happy Helming!
NAME: lacework-agent
LAST DEPLOYED: Wed Jan 17 09:27:33 2024
NAMESPACE: lacework
STATUS: deployed
REVISION: 2
```
Thanks for flagging the broken link in the readme, I will fix that shortly- https://docs.lacework.net/onboarding/deploy-on-kubernetes#install-using-helm

**Comment by joebowbeer** [comment]
@abapat thanks for the corrections. I see the tgz.

**Comment by jycamier** [comment]
It works now. Thank you
