### ISSUE TITLE
Kubernetes 1.29 compatibility

### ISSUE THREAD

**Issue by joebowbeer** [lacework/helm-charts#228]
According to the docs, lacework agent is not compatible with Kubernetes 1.29

https://docs.lacework.net/onboarding/deploy-on-kubernetes#supported-kubernetes-environments

The current version appears to be using the following APIs that were [removed in 1.29](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#flowcontrol-resources-v129):
* /apis/flowcontrol.apiserver.k8s.io/v1beta2/flowschemas
* /apis/flowcontrol.apiserver.k8s.io/v1beta2/prioritylevelconfigurations

**Comment by catz-lw** [comment]
Hi Joe. Thanks for the report. I'm curious, how are you determining which deprecated APIs the agent is using?

**Comment by vglen** [comment]
> Hi Joe. Thanks for the report. I'm curious, how are you determining which deprecated APIs the agent is using?

It's listed in the EKS console under upgrade insights from 1.28 to 1.29. Basically the api moves to `beta3`

```
/apis/flowcontrol.apiserver.k8s.io/v1beta3/flowschemas
/apis/flowcontrol.apiserver.k8s.io/v1beta3/prioritylevelconfigurations
```

**Comment by treyhyde** [comment]
I'd hate to me-too this but it's everyone.  Lacework is blocking our upgrade to 1.29 and this has been a warning for a while.

**Comment by vglen** [comment]
I think the calls are from the app and not in the chart. I upgraded from 6.6 to 6.11 today and waiting for EKS insights checks. I'll report back.

**Comment by vglen** [comment]
> I think the calls are from the app and not in the chart. I upgraded from 6.6 to 6.11 today and waiting for EKS insights checks. I'll report back.

The checks did not clear and ran after upgrading to 6.11 on numerous 1.28 clusters.

**Comment by catz-lw** [comment]
@vglen  and @treyhyde  It is safe to upgrade the cluster agent. The agent doesn't require the use of the deprecated and removed APIs, but it will query whatever APIs are present in a given version of Kubernetes. The warnings are a **_heuristic_**, and do not mean "this product will break" but rather than "this product might break". Future versions of the cluster agent will exclude deprecrated APIs from this scraping to avoid the warnings.

**Comment by joebowbeer** [comment]
@catz-lw Can you update the supported versions?

https://docs.lacework.net/onboarding/deploy-on-kubernetes

**Comment by catz-lw** [comment]
> @catz-lw Can you update the supported versions?
> 
> https://docs.lacework.net/onboarding/deploy-on-kubernetes

@joebowbeer Yes, sorry for the confusion, official documentation will land soon.
