### ISSUE TITLE
[agent] daemonset affinity is not used in template

### ISSUE THREAD

**Issue by demikl** [lacework/helm-charts#37]
Hi.

The chart exposes daemonset affinity through `.Values.daemonset.affinity` but this value is not used in the Daemonset template. It's needed for me to avoid the pod being targeted on EKS Fargate nodes.

**Comment by cirego** [comment]
Hi @demikl, what a strange coincidence. I just removed the affinity field from our internal branch yesterday. I will file an internal tracking ticket to add it back. Thanks!

**Comment by cirego** [comment]
I have posted the PR for internal review and this ticket will autoclose once that PR is merged. Please expect this change with the 5.3 release!
