### ISSUE TITLE
Lacework Agent Helm chart depends on Docker

### ISSUE THREAD

**Issue by sarahhodne** [lacework/helm-charts#47]
I'm looking into switching away from Docker as our container runtime in preparation for upgrading to Kubernetes 1.23, which no longer has dockershim.

However, I see that the lacework-agent Helm chart still hardcodes the Docker socket mount, even though it seems the agent itself [supports containerd](https://docs.lacework.com/supported-operating-systems#container-runtime).

Could the chart be updated to make this path customisable, so it's possible to use with Kubernetes 1.23 or later?

**Comment by carlosjgp** [comment]
Same here.

We are using K8s 1.21 but we use contained already. 1.22 would remove Docker completely

On top of that, we use EKS with BottleRocket OS AMIs which mounts the container shim here
https://github.com/bottlerocket-os/bottlerocket/blob/42c9954aba198ff8880094e389f372ce304f2dbe/packages/kubernetes-1.21/kubelet-exec-start-conf#L15

**Comment by rnalexlacework** [comment]
This is tracked here https://lacework.atlassian.net/browse/RAIN-31328, this needs prioritization

**Comment by reegnz** [comment]
Hi, any update on when one could use containerd with your helm charts? Currently the only solution I'm seeing is to either fork, or do some post-render manifest modification.

**Comment by cirego** [comment]
Hi @reegnz, I failed to mark this issue as closed when we released the 5.6 charts. The dockershim mounts have been removed!
