### ISSUE TITLE
Allow Proxy scanner chart to get the account credentials in a secure way

### ISSUE THREAD

**Issue by carlosjgp** [lacework/helm-charts#62]
Instead of providing the access token in plain text through Helm values, which is fine for testing purposes, allow the sensitive values to be provided from a K8s secret as VolumeMount or Environment variables

This would be the minimum step up in security to get a production-ready deployment for us

**Comment by michael-zhou-lw** [comment]
Thanks for the feedback, we've been looking into better ways to pass secrets into the scanner. In this case, are you saying to move the lacework access token or registry credentials or both to K8s secrets/environment variables?

**Comment by cirego** [comment]
@michael-zhou-lw, the agent team recently added support for existing secrets to the agent helm charts to satisfy this use case: https://docs.lacework.com/deploy-on-kubernetes#specify-an-existing-secret. Happy to chat about how we did this!

**Comment by cirego** [comment]
For reference, we added this support to the agent Helm charts in #56.

**Comment by michael-zhou-lw** [comment]
@cirego This is awesome! I'll have a look.

**Comment by michael-zhou-lw** [comment]
@carlosjgp We'll be adding this functionality to use k8s secrets for the access token in the next couple weeks.

**Comment by michael-zhou-lw** [comment]
@carlosjgp This functionality has been added to our latest admission controller and proxy scanner helm charts. Thanks!
