### ISSUE TITLE
Allow adding custom annotations to Admission Controller and Proxy Scanner

### ISSUE THREAD

**Issue by carlosjgp** [lacework/helm-charts#63]
This is very helpful when Secrets or configmap content changes. Using [Stakater Reloader](https://github.com/stakater/Reloader) annotations these deployments PODs would be restarted and configuration would be refreshed
At the moment I have to restart the PODs manually each time

Another common technique is to use [Helm checksum annotations](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments)

admission-controller
https://github.com/lacework/helm-charts/blob/1e5139040a65ad6fb019a16f11edd31674ec09be/admission-controller/templates/deployment.yaml#L11

proxy-scanner
https://github.com/lacework/helm-charts/blob/1e5139040a65ad6fb019a16f11edd31674ec09be/proxy-scanner/templates/deployment.yaml#L14

**Comment by michael-zhou-lw** [comment]
Thanks for the feedback! Will open an internal ticket to add and test this.

**Comment by michael-zhou-lw** [comment]
@carlosjgp This has been added to the latest proxy scanner helm chart, we'll add this to the admission controller helm chart next.
