### ISSUE TITLE
Need option to set Requests and limits for proxyscanner deployment

### ISSUE THREAD

**Issue by saviovettoor** [lacework/helm-charts#65]
Lacework proxyscanner helm chart, didn't support pass resource Requests and limits values over values.yaml file.

**Comment by michael-zhou-lw** [comment]
@saviovettoor This has been added to the latest proxy scanner helm chart, thanks for the feedback! https://github.com/lacework/helm-charts/commit/bf691439b64602fa15df7d0216949dc5f3d7bf19
