### ISSUE TITLE
5.6.0 gives error if your not setting the "optional" values

### ISSUE THREAD

**Issue by jbiskur** [lacework/helm-charts#79]
The values in the values.yaml file as well as the comments suggest that these values are optional

https://github.com/lacework/helm-charts/blob/80f998e6d6766a5141aa9c6eab2c946cd868c3b3/lacework-agent/values.yaml#L38-L51

These values are required in the schema file

https://github.com/lacework/helm-charts/blob/80f998e6d6766a5141aa9c6eab2c946cd868c3b3/lacework-agent/values.schema.json#L142-L150

So conflicting information here :) are they required or optional ?

**Comment by cirego** [comment]
Hi @jbiskur, I apologize for the confusion, as you're not the only one that has run into this (#72).

The original intention was that, although the schema file requires that the fields be present, they default to `null` values, hence the note about them being optional. However, as you and others have noted, when using a `values` file that does not include a `fim` object in the `laceworkConfig` object, the schema checking fails. We hope to have a fix for this shortly and may need to break the existing API for configuring `fim`.

In the meantime, we do have a workaround documented in more detail here: https://github.com/lacework/helm-charts/issues/72#issuecomment-1135248696

**Comment by joebowbeer** [comment]
Relates to #96

**Comment by joebowbeer** [comment]
The four fim properties in question (coolingPeriod, crawlInterval, noAtime, runAt) should either:
* Have `null` removed from their types and a non-null default value added to `values.yaml`, or
* Should be removed from the list of required properties

**Comment by cirego** [comment]
I have a PR out for review that will remove these fields from being required. We should have this available in the next release of our charts.
