### ISSUE TITLE
Support for EKS IRSA for Proxy Scanner

### ISSUE THREAD

**Issue by devops-corgi** [lacework/helm-charts#94]
As many of you are probably aware, Amazon EKS supports IRSA:
* https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

An easy way to configure it is to either allow the chart to use a custom ServiceAccount, or to add a field to add annotations to the existing ServiceAccount.  IE something like this:

In values.yaml:

```
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::1111111111:role/lacework-proxy-agent
```

Then in serviceaccount.yaml:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  annotations:
    {{- range $key, $val := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $val }}
    {{- end }}
```

**Comment by michael-zhou-lw** [comment]
Hey @devops-corgi, thanks for raising this issue. This has been added in https://github.com/lacework/helm-charts/pull/147.
