### ISSUE TITLE
Remove scrape times from required

### ISSUE THREAD

**Issue by joebowbeer** [lacework/helm-charts#96]
Why are [these](https://github.com/lacework/helm-charts/blob/main/lacework-agent/values.schema.json#L69-L77) scrape times required?

```yaml
        "clusterAgent": {
            "type": "object",
            "required": [
                "image",
                "enable",
                "clusterType",
                "scrapeInitialDelayMins",
                "scrapeIntervalMins"
            ],
```

Their type declarations include `null`.

Suggested fix:
* If `null` is allowed then remove them from required
* If they are required, provide non-null values in `values.yaml` and remove null from their types

_Originally posted by @joebowbeer in https://github.com/lacework/helm-charts/pull/85#discussion_r944901002_

**Comment by cirego** [comment]
Hi @joebowbeer, is there a particular error that you ran into the with the `clusterAgent` configuration? The `fim` configuration problems stem from how Helm merges objects (it does not perform a deep merge). However, `clusterAgent` is defined at the top-level, which means the merge logic should work.

Where possible, we try to make sure our arguments are strongly typed so that customers can discover misconfigurations faster. Happy to reconsider this if you ran into an issue where this didn't work as expected.

**Comment by joebowbeer** [comment]
@cirego The error I get unless I provide 0 values for the _unset_ scrape properties is the same error as when I don't provide values for the unset parts of clusterAgent.

The clusterAgent issue is more serious, by the way, because it forces a specific time for runAt instead of using the less-specific default behavior.

I believe these problems with clusterAgent and fim have nothing to do with deep merging.

In fact, helm _does_ deep merge dicts and nested dicts, as expected:

https://github.com/helm/helm/issues/3486#issuecomment-1199927701

> I am seeing the expected behavior on v3.9.0.

I think the problem stems from requiring a property that is nullable. I suspect there are some helm-specific issues that are preventing this from working as intended:

https://github.com/helm/helm-www/issues/903#issuecomment-792798261

> Unset values work, but JSON Schema (and/or the validator used in helm) handles "unset" and "set to null" differently w.r.t. required. Also, we can't use null in all places, because helm doesn't honor "type" = ["string", "null"], unfortunately.

**Comment by cirego** [comment]
@joebowbeer, thanks for that explainer. It looks like I need to learn a bit more about Helm's behavior so that we can fix this the right way.

**Comment by cirego** [comment]
I have a PR out for review that will remove these fields from being required. We should have this available in the next release of our charts.
