### ISSUE TITLE
Document laceworkConfig.env

### ISSUE THREAD

**Issue by joebowbeer** [lacework/helm-charts#97]
The schema says this value is used to "Give your k8s environment a friendly name"

The only example I can find in the [docs](https://docs.lacework.com/onboarding/deploy-on-kubernetes#daemonset-deployment-using-a-secret) is: `"Env":"k8s"`

Is this displayed in the dashboard? Is there a way to filter on this?

**Comment by joebowbeer** [comment]
Answered: I found more documentation:

https://docs.lacework.com/onboarding/add-agent-tags

**Comment by cirego** [comment]
Hi @joebowbeer, thanks for raising this issue. We'll add a link to this documentation the Helm charts as well.
